stages:
  - build

build:
  image: electronuserland/builder
  stage: build
  script:
    - yarn
    - yarn dist:win
    - yarn dist:linux
  artifacts:
    expire_in: 30 days
    paths:
      - ./dist/
  only:
    - master

